---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-credentials
type: Opaque
stringData:
  identities.yaml: |-
    credentials:
    - username: developer
      password: developer
    - username: admin
      password: password
      roles:
        - admin
    - username: alvaro
      password: openshift
      roles:
        - application
